### PR TITLE
Refactored doesUsernameExist and getUserByUsername to correctly check…

### PR DESCRIPTION
**Pull request by vanessuniq**
username is saved as lower case  in firestore once a user is created. I refactored the doesUsernameExist and getUserByUsername for correct comparison

### CODE REVIEW

**Review by 9314610Jc — APPROVED** [review]

**Comment by karlhadwen** [comment]
Sorry I've only just seen this, can you reformat and add an empty line at the EOF?

**Comment by vanessuniq** [comment]
The file has been reformatted.

**Review by vanessuniq — COMMENTED** [review]
File reformatted

**Review by karlhadwen — APPROVED** [review]

**Comment by karlhadwen** [comment]
Thank you!

**Pull request merged**
